require:
  - rubocop-rails
  # - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'test/**/*'

Documentation:
  Enabled: false